### ISSUE TITLE
owr_init() API update

### ISSUE THREAD

**Issue by philn** [EricssonResearch/openwebrtc#209] opened 2015-03-05 10:37 UTC
- I think it should be possible to invoke owr_init() multiple times without critical warning emission on second call
- I'm not sure to see why owr_init_with_main_context() is useful... Couldn't we have owr_init() use the default main context and assume the application would run a GMainLoop itself? This way we could get rid of owr_run()

**Comment by sdroege** [comment] 2015-03-05 10:43
I would prefer a single, idempotent owr_init() too, which would then take the thread default main context for all its stuff. And then get rid of owr_run() and let the app just run a main loop on whatever main context is wants.

The current init API is very confusing

**Comment by sdroege** [comment] 2015-03-09 08:36
Duplicate of https://github.com/EricssonResearch/openwebrtc/issues/143

**Closed by sdroege** 2015-03-09 08:36 UTC
