### ISSUE TITLE
Build failed - "Undefined reference to gst_plugin_dtls_register"

### ISSUE THREAD

**Issue by simonpi** [EricssonResearch/openwebrtc#270] opened 2015-03-24 09:15 UTC
Hi,

I'm having an issue while building OpenWebRTC on Ubuntu 14.04 64bit as recommended.
I've been following everything described in here:
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

Bootstrapping and building dependencies went well. But when I am building OpenWebRTC for linux I have the following error:

GISCAN Owr-0.1.gir
./.libs/libopenwebrtc.so: undefined reference to 'gst_plugin_dtls_register'
collect2: error: ld returned 1 exit status

Do you know how to solve this?

Edit. I just relized that someone had the same problem. But do you know how to solve it anyway, without the need to use cerbero?

**Comment by sdroege** [comment] 2015-03-24 09:28
Duplicate of #266

**Comment by nirbheek** [comment] 2015-03-24 09:28
This is the same bug as https://github.com/EricssonResearch/openwebrtc/issues/266

**Closed** 2015-03-24 09:28 UTC
