### ISSUE TITLE
Cerbero owr build error

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc#175] opened 2015-02-16 09:29 UTC
As report by mail:
```
[(38/39) openwebrtc-gst-plugins-static -> fetch ]
[(38/39) openwebrtc-gst-plugins-static -> extract ]
[(38/39) openwebrtc-gst-plugins-static -> configure ]
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.guess to /Users/ephilip/cerbero/sources/ios_universal/armv7s/openwebrtc-gst-plugins-static-0.0.1/config.guess
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.sub to /Users/ephilip/cerbero/sources/ios_universal/armv7s/openwebrtc-gst-plugins-static-0.0.1/config.sub
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.guess to /Users/ephilip/cerbero/sources/ios_universal/x86/openwebrtc-gst-plugins-static-0.0.1/config.guess
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.sub to /Users/ephilip/cerbero/sources/ios_universal/x86/openwebrtc-gst-plugins-static-0.0.1/config.sub
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.guess to /Users/ephilip/cerbero/sources/ios_universal/armv7/openwebrtc-gst-plugins-static-0.0.1/config.guess
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.sub to /Users/ephilip/cerbero/sources/ios_universal/armv7/openwebrtc-gst-plugins-static-0.0.1/config.sub
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.guess to /Users/ephilip/cerbero/sources/ios_universal/arm64/openwebrtc-gst-plugins-static-0.0.1/config.guess
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.sub to /Users/ephilip/cerbero/sources/ios_universal/arm64/openwebrtc-gst-plugins-static-0.0.1/config.sub
[(38/39) openwebrtc-gst-plugins-static -> compile ]
[(38/39) openwebrtc-gst-plugins-static -> install ]
[(38/39) openwebrtc-gst-plugins-static -> post_install ]
[(38/39) openwebrtc-gst-plugins-static -> merge ]
[(39/39) openwebrtc -> fetch ]
[(39/39) openwebrtc -> extract ]
[(39/39) openwebrtc -> configure ]
Recipe 'openwebrtc' failed at the build step 'configure'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/recipe.py", line 263, in <lambda>
    setattr(cls, step, lambda self, name=step: step_func(self, name))
  File "./cerbero/build/recipe.py", line 408, in _do_step
    stepfunc()
  File "/Users/ephilip/Code/cerbero/recipes/openwebrtc.recipe", line 149, in configure
    os.chdir(gir_file_path)
OSError: [Errno 2] No such file or directory: '/Library/Frameworks/OpenWebRTC.framework/Versions/0.1/share/gir-1.0'
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort
```

@nirbheek?

**Comment by sdroege** [comment] 2015-02-16 10:36
You first have to build the OSX version of OpenWebRTC. Only then you can build iOS.

**Comment by stefanalund** [comment] 2015-02-16 10:42
I will tell him. Can we close the issue then?

**Comment by sdroege** [comment] 2015-02-16 10:43
Yes, unless that wasn't the problem and something else is wrong. Let's reopen then.

**Comment by emphilip** [comment] 2015-02-16 13:49
Hello

I'm the OR of this issue.  I did start by building the OSX version of OpenWebRTC (I am on Yosemite).  Navigating to ~/Library/Frameworks, I have some sort of recursive directory created that may be part of the issue?  

![screen shot 2015-02-16 at 8 39 39 am](https://cloud.githubusercontent.com/assets/871072/6212856/ae266f86-b5b7-11e4-8185-4bdc53937e55.png)

Here is the log when I tried building the OSX version:
```
edwardMacbook:cerbero edward$ ./cerbero-uninstalled -c config/osx-x86-64.cbc package openwebrtc
WARNING: Using default configuration because /Users/ephilip/.cerbero/cerbero.cbc is missing
Building the following recipes: libiconv gettext libffi zlib glib orc bzip2 gobject-introspection bionic-fixup gtk-doc-lite gstreamer-1.0 gst-plugins-base-1.0 libvpx gst-plugins-good-1.0 openh264 opus libsrtp gst-plugins-bad-1.0 libnice gstreamer-1.0-static gst-plugins-base-1.0-static gst-plugins-good-1.0-static gst-plugins-bad-1.0-static libnice-static intltool gnome-js-common seed json-glib libxml2 gmp nettle libtasn1 gnutls glib-networking libsoup openssl openwebrtc-gst-plugins openwebrtc openwebrtc-osx-framework openwebrtc-gst-plugins-static
[(1/40) libiconv -> fetch ]
-----> Fetching tarball http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.14.tar.gz to /Users/ephilip/cerbero/sources/local/libiconv-1.14/libiconv-1.14.tar.gz
File /Users/ephilip/cerbero/sources/local/libiconv-1.14/libiconv-1.14.tar.gz already downloaded.
[(1/40) libiconv -> extract ]
-----> Extracting tarball to /Users/ephilip/cerbero/sources/darwin_x86_64/libiconv-1.14
Unpacking /Users/ephilip/cerbero/sources/local/libiconv-1.14/libiconv-1.14.tar.gz in /Users/ephilip/cerbero/sources/darwin_x86_64
[(1/40) libiconv -> configure ]
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.guess to /Users/ephilip/cerbero/sources/darwin_x86_64/libiconv-1.14/build-aux/config.guess
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.guess to /Users/ephilip/cerbero/sources/darwin_x86_64/libiconv-1.14/libcharset/build-aux/config.guess
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.sub to /Users/ephilip/cerbero/sources/darwin_x86_64/libiconv-1.14/build-aux/config.sub
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.sub to /Users/ephilip/cerbero/sources/darwin_x86_64/libiconv-1.14/libcharset/build-aux/config.sub
[(1/40) libiconv -> compile ]
[(1/40) libiconv -> install ]
[(1/40) libiconv -> post_install ]
[(2/40) gettext -> fetch ]
-----> Fetching tarball http://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.4.tar.gz to /Users/ephilip/cerbero/sources/local/gettext-0.19.4/gettext-0.19.4.tar.gz
File /Users/ephilip/cerbero/sources/local/gettext-0.19.4/gettext-0.19.4.tar.gz already downloaded.
[(2/40) gettext -> extract ]
-----> Extracting tarball to /Users/ephilip/cerbero/sources/darwin_x86_64/gettext-0.19.4
Unpacking /Users/ephilip/cerbero/sources/local/gettext-0.19.4/gettext-0.19.4.tar.gz in /Users/ephilip/cerbero/sources/darwin_x86_64
[(2/40) gettext -> configure ]
[(2/40) gettext -> compile ]
[(2/40) gettext -> install ]
[(2/40) gettext -> post_install ]
[(3/40) libffi -> fetch ]
[(3/40) libffi -> extract ]
[(3/40) libffi -> configure ]
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.guess to /Users/ephilip/cerbero/sources/darwin_x86_64/libffi-3.2.1/config.guess
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.sub to /Users/ephilip/cerbero/sources/darwin_x86_64/libffi-3.2.1/config.sub
[(3/40) libffi -> compile ]
[(3/40) libffi -> install ]
[(3/40) libffi -> post_install ]
[(4/40) zlib -> already built ]
[(5/40) glib -> fetch ]
-----> Fetching tarball http://ftp.acc.umu.se/pub/GNOME/sources/glib/2.42/glib-2.42.0.tar.xz to /Users/ephilip/cerbero/sources/local/glib-2.42.0/glib-2.42.0.tar.xz
File /Users/ephilip/cerbero/sources/local/glib-2.42.0/glib-2.42.0.tar.xz already downloaded.
[(5/40) glib -> extract ]
-----> Extracting tarball to /Users/ephilip/cerbero/sources/darwin_x86_64/glib-2.42.0
Unpacking /Users/ephilip/cerbero/sources/local/glib-2.42.0/glib-2.42.0.tar.xz in /Users/ephilip/cerbero/sources/darwin_x86_64
[(5/40) glib -> configure ]
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.guess to /Users/ephilip/cerbero/sources/darwin_x86_64/glib-2.42.0/config.guess
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.sub to /Users/ephilip/cerbero/sources/darwin_x86_64/glib-2.42.0/config.sub
[(5/40) glib -> compile ]
[(5/40) glib -> install ]
[(5/40) glib -> post_install ]
[(6/40) orc -> already built ]
[(7/40) bzip2 -> already built ]
[(8/40) gobject-introspection -> already built ]
[(9/40) bionic-fixup -> already built ]
[(10/40) gtk-doc-lite -> already built ]
[(11/40) gstreamer-1.0 -> already built ]
[(12/40) gst-plugins-base-1.0 -> already built ]
[(13/40) libvpx -> already built ]
[(14/40) gst-plugins-good-1.0 -> already built ]
[(15/40) openh264 -> already built ]
[(16/40) opus -> already built ]
[(17/40) libsrtp -> already built ]
[(18/40) gst-plugins-bad-1.0 -> already built ]
[(19/40) libnice -> already built ]
[(20/40) gstreamer-1.0-static -> already built ]
[(21/40) gst-plugins-base-1.0-static -> already built ]
[(22/40) gst-plugins-good-1.0-static -> already built ]
[(23/40) gst-plugins-bad-1.0-static -> already built ]
[(24/40) libnice-static -> already built ]
[(25/40) intltool -> already built ]
[(26/40) gnome-js-common -> already built ]
[(27/40) seed -> already built ]
[(28/40) json-glib -> already built ]
[(29/40) libxml2 -> already built ]
[(30/40) gmp -> already built ]
[(31/40) nettle -> already built ]
[(32/40) libtasn1 -> already built ]
[(33/40) gnutls -> already built ]
[(34/40) glib-networking -> already built ]
[(35/40) libsoup -> already built ]
[(36/40) openssl -> already built ]
[(37/40) openwebrtc-gst-plugins -> already built ]
[(38/40) openwebrtc -> fetch ]
[(38/40) openwebrtc -> extract ]
[(38/40) openwebrtc -> configure ]
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.guess to /Users/ephilip/cerbero/sources/darwin_x86_64/openwebrtc-0.0.1/config.guess
-----> copying /Users/ephilip/Code/cerbero/data/autotools/config.sub to /Users/ephilip/cerbero/sources/darwin_x86_64/openwebrtc-0.0.1/config.sub
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I/Library/Frameworks/OpenWebRTC.framework/Versions/0.1/share/aclocal -I/Users/ephilip/cerbero/build-tools/share/aclocal --force 
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: configure.ac: tracing
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: running: /Users/ephilip/cerbero/build-tools/bin/autoconf --force
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: running: /Users/ephilip/cerbero/build-tools/bin/autoheader --force
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
configure.ac:13: installing './compile'
configure.ac:16: installing './config.guess'
configure.ac:16: installing './config.sub'
configure.ac:9: installing './install-sh'
configure.ac:9: installing './missing'
bindings/java/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
configure: WARNING: unrecognized options: --disable-maintainer-mode
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether clang understands -c and -o together... rm: conftest.dSYM: is a directory
yes
checking for style of include used by make... GNU
checking dependency style of clang... gcc3
checking for clang option to accept ISO C99... none needed
checking for clang option to accept ISO Standard C... (cached) none needed
checking for gcc... gcc
checking whether we are using the GNU Objective C compiler... yes
checking whether gcc accepts -g... yes
checking dependency style of gcc... gcc3
checking build system type... x86_64-apple-darwin12
checking host system type... x86_64-apple-darwin12
checking target system type... x86_64-apple-darwin12
checking how to print strings... printf
checking for a sed that does not truncate output... /Users/ephilip/cerbero/build-tools/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by clang... ld
checking if the linker (ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... nm
checking the name lister (nm) interface... rm: conftest.dSYM: is a directory
BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin12 file names to x86_64-apple-darwin12 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin12 file names to toolchain format... func_convert_file_noop
checking for ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... rm: conftest.dSYM: is a directory
no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse nm output from clang object... rm: conftest.dSYM: is a directory
ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... clang -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if clang supports -fno-rtti -fno-exceptions... yes
checking for clang option to produce PIC... -fno-common -DPIC
checking if clang PIC flag -fno-common -DPIC works... yes
checking if clang static flag -static works... no
checking if clang supports -c -o file.o... yes
checking if clang supports -c -o file.o... (cached) yes
checking whether the clang linker (ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin12 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking for GSTREAMER... no
configure: error: Package requirements (gstreamer-1.0 >= 1.4 gstreamer-rtp-1.0 >= 1.4 gstreamer-video-1.0 >= 1.4 gstreamer-app-1.0 >= 1.4) were not met:

No package 'gstreamer-1.0' found
No package 'gstreamer-rtp-1.0' found
No package 'gstreamer-video-1.0' found
No package 'gstreamer-app-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GSTREAMER_CFLAGS
and GSTREAMER_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Running command 'mkdir -p m4 && gtkdocize && autoreconf -fiv'
Running command './configure --prefix /Library/Frameworks/OpenWebRTC.framework/Versions/0.1 --libdir /Library/Frameworks/OpenWebRTC.framework/Versions/0.1/lib  --disable-gtk-doc --disable-static                 --disable-owr-static --enable-shared --disable-maintainer-mode  --disable-silent-rules  --enable-introspection  --build=x86_64-apple-darwin12'

Recipe 'openwebrtc' failed at the build step 'configure'
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort
```

I'm going to try the entire process again from scratch and will provide the entire console log by the EOD. 

Thanks

**Comment by stefanalund** [comment] 2015-02-16 13:56
The `OpenWebRTC.framework` that you should use for iOS development is found in:

```
~/Library/Developer/OpenWebRTC/iPhone.sdk/OpenWebRTC.framework
```

**Comment by emphilip** [comment] 2015-02-16 14:06
I just had a thought - is the bootstrapping step for the MacOSX build in the build instructions?

**Comment by sdroege** [comment] 2015-02-16 14:10
@emphilip Did you delete any files since a previous build? It believes that you already built gstreamer-1.0 and others, but can't find during the build.

Maybe run
./cerbero-uninstalled -c config/osx-x86-64.cbc wipe --build-tools
[type yes]
./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap
./cerbero-uninstalled -c config/osx-x86-64.cbc package openwebrtc

If this still fails the same way, please attach the generated config.log from openwebrtc's configure.

**Comment by ijsf** [comment] 2015-02-16 14:22
I also experienced this issue. In my case, it was caused by the fact that I had not installed cerbero in the home directory (as mentioned in the docs).

After removing everything and installing cerbero in ~/cerbero, and doing a build I didn't experience any errors anymore.

**Comment by emphilip** [comment] 2015-02-16 14:23
@sdroege I didn't delete any files, but i'm trying the entire process from scratch for better traceability.

```
edwardMacbook:~ edward$ ls
Applications	Code		Desktop		Documents	Downloads	Library		Movies		Music		Pictures	Public		VirtualBox VMs	dumps
edwardMacbook:~ edward$ git clone https://github.com/nirbheek/cerbero.git
Cloning into 'cerbero'...
remote: Counting objects: 18188, done.
remote: Compressing objects: 100% (4401/4401), done.
remote: Total 18188 (delta 13731), reused 18139 (delta 13701)
Receiving objects: 100% (18188/18188), 4.52 MiB | 1.55 MiB/s, done.
Resolving deltas: 100% (13731/13731), done.
Checking connectivity... done.
edwardMacbook:~ edward$ sudo mkdir /Library/Frameworks/OpenWebRTC.framework
Password:
edwardMacbook:~ edward$ sudo chown $UID /Library/Frameworks/OpenWebRTC.framework/
edwardMacbook:~ edward$ cd cerbero/
edwardMacbook:cerbero edward$ mkdir -p dist
edwardMacbook:cerbero edward$ mkdir -p /Library/Frameworks/OpenWebRTC.framework/Versions/0.1
edwardMacbook:cerbero edward$ ln -s /Library/Frameworks/OpenWebRTC.framework/Versions/0.1 dist/darwin_x86_64
edwardMacbook:cerbero edward$ cd cerbero
edwardMacbook:cerbero edward$ ./cerbero-uninstalled -c config/osx-x86-64.cbc wipe --build-tools
-bash: ./cerbero-uninstalled: No such file or directory
edwardMacbook:cerbero edward$ cd ..
edwardMacbook:cerbero edward$ ./cerbero-uninstalled -c config/osx-x86-64.cbc wipe --build-tools
WARNING: Using default configuration because /Users/ephilip/.cerbero/cerbero.cbc is missing
WARNING!!!
This command will delete cerbero's build cache, the sources directory, and the builds directory to reset the build system to its initial state.
The following paths will be removed:
/Users/ephilip/cerbero/darwin_x86_64.cache
/Library/Frameworks/OpenWebRTC.framework/Versions/0.1
/Users/ephilip/cerbero/logs/darwin_x86_64
/Users/ephilip/cerbero/sources/darwin_x86_64
/Users/ephilip/cerbero/build-tools.cache
/Users/ephilip/cerbero/build-tools
/Users/ephilip/cerbero/sources/build-tools
Do you want to continue? [yes/no] yes
Are you sure? [yes/no] yes
-----> Removing path: /Users/ephilip/cerbero/darwin_x86_64.cache
-----> Removing path: /Library/Frameworks/OpenWebRTC.framework/Versions/0.1
Running command 'rm -rf /Library/Frameworks/OpenWebRTC.framework/Versions/0.1'
-----> Removing path: /Users/ephilip/cerbero/logs/darwin_x86_64
Running command 'rm -rf /Users/ephilip/cerbero/logs/darwin_x86_64'
-----> Removing path: /Users/ephilip/cerbero/sources/darwin_x86_64
Running command 'rm -rf /Users/ephilip/cerbero/sources/darwin_x86_64'
-----> Removing path: /Users/ephilip/cerbero/build-tools.cache
-----> Removing path: /Users/ephilip/cerbero/build-tools
Running command 'rm -rf /Users/ephilip/cerbero/build-tools'
-----> Removing path: /Users/ephilip/cerbero/sources/build-tools
edwardMacbook:cerbero edward$ ./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap
WARNING: Using default configuration because /Users/ephilip/.cerbero/cerbero.cbc is missing
WARNING: No bootstrapper for the distro version osx_yosemite
File /var/folders/kn/68k97p2j3dl0k_m8tn7v8fy00000gn/T/tmpeNMDlC already downloaded.
Running command 'chmod +x /var/folders/kn/68k97p2j3dl0k_m8tn7v8fy00000gn/T/tmpeNMDlC'
Running command 'sudo /var/folders/kn/68k97p2j3dl0k_m8tn7v8fy00000gn/T/tmpeNMDlC XML::Parser'
Password:
WARNING: Using default configuration because /Users/ephilip/.cerbero/cerbero.cbc is missing
WARNING: Could not recover status
Building the following recipes: libiconv gettext xz tar m4 autoconf automake libtool pkg-config orc-tool gettext-m4 sed gettext-tools libffi zlib glib gobject-introspection gnome-common gtk-doc-lite gperf intltool yasm bison flex
[(1/24) libiconv -> fetch ]
....

```

I'll follow up here when this is complete.

**Comment by stefanalund** [comment] 2015-02-16 16:33
@sdroege the wiki does not say anything about deleting files before rebuilding. Could you add that step to the instructions?

**Comment by sdroege** [comment] 2015-02-16 22:58
@stefanalund that's not necessary, I just asked that in case @emphilip had an inconsistent state currently... which is how his build problem looked like.

**Comment by superdump** [comment] 2015-02-17 06:25
@sdroege I suppose it could be in a troubleshooting/ things to try in case of errors section.

**Comment by emphilip** [comment] 2015-02-17 07:58
Thank you for all the support.  @ijsf was right - I had created a repository in a subdirectory of my home directory instead of my home directory itself.

I've been able to successfully compile and run the framework & simpleDemo application.  Though the remote video feed just shows up as a black box, the framework builds and integrates really nicely.  @stefanalund @sdroege  Thanks a ton for the support.  The wiki is really clear now as well.

You can close this ticket.

**Closed** 2015-02-17 18:19 UTC

**Comment by vdev2015** [comment] 2015-03-25 11:40
Hi @emphilip I have tried your mentioned steps and during the packaging process got this issue:

D -MP -MF .deps/libgobject_2_0_la-gbinding.Tpo -c gbinding.c -o libgobject_2_0_la-gbinding.o >/dev/null 2>&1
mv -f .deps/libgobject_2_0_la-gboxed.Tpo .deps/libgobject_2_0_la-gboxed.Plo
mv -f .deps/libgobject_2_0_la-gbinding.Tpo .deps/libgobject_2_0_la-gbinding.Plo
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Running command 'make -j4'

Recipe 'glib' failed at the build step 'compile'
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort

Please, help me to fix this issue guys.

**Comment by nirbheek** [comment] 2015-03-27 08:13
@vdev2015 Your issue seems different from the one discussed on this issue. Could you open a new issue with a full log of the failure?

**Comment by superdump** [comment] 2015-03-27 09:47
I saw the issue @vdev2015 pasted above during my build efforts and I think it has been fixed. The pasted text is not actually the error, that's just where one of the make jobs stops I think.

@vdev2015 Can you try to update cerbero according to the wiki ( https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero#updating ) and create a new issue if you still have problems?
