### ISSUE TITLE
Dropping the first packet(s) and thus the keyframe

### ISSUE THREAD

**Issue by sdroege** [EricssonResearch/openwebrtc#186] opened 2015-02-19 17:35 UTC
We currently send packets to nicesink already before it is connected. That will cause it to drop packets, especially it will drop our first packet(s) and thus the keyframe.

Looking for the correct fix now.

**Comment by sdroege** [comment] 2015-02-19 17:48
A patch will be here once fd.o has updated things: http://cgit.freedesktop.org/~slomo/libnice/
Why is it impossible to attach non-image files to the github bugtracker? Completely useless...

I think this patch is not correct though, but it gives me the first frame instantaneous with test-send-receive. Less than a second.
We probably have to do something like this at the openwebrtc level instead, but that patch shows at least that it can work and what the problem is.

**Comment by sdroege** [comment] 2015-02-19 17:49
http://cgit.freedesktop.org/~slomo/libnice/commit/?id=dc39f9c302053c8c91d360f4af2b9cbcbd85ef56 to be specific

**Comment by sdroege** [comment] 2015-02-19 18:20
The fix inside owr would probably be the following:
- we wait until the agent has connected the stream
- and only then start the transport agent pipeline, so that at the moment the first frame is encoded and payloaded, we can immediately send it

**Comment by superdump** [comment] 2015-02-19 22:49
I think github's idea is that you paste your patch into http://gist.guthub.com/ publish it and link it in the issue. Not the most shiny thing ever. It could recognize patches and do it for you...

**Comment by superdump** [comment] 2015-02-19 22:49
Oops... http://gist.github.com/

**Comment by sdroege** [comment] 2015-02-20 08:32
So apparently a similar patch for that was created by @alessandrod and is in the build scripts, but not at libnice upstream or in cerbero: https://github.com/EricssonResearch/openwebrtc-build-scripts/blob/master/dependencies/libnice_sink_wait_candidates.patch

I'll implement the fix in owr today so we can finally get rid of this. My current thinking is that the current behaviour in nicesink is the intended one, so we have to do things differently in owr instead.

**Comment by sdroege** [comment] 2015-02-20 11:59
Basically this requires rewiring things in the transport agent to start at least the send DTLS elements later once nicesink can send data, ideally also adding the send payload and source to be started at that point. We could of course get away with a pad block, but that will cause some backlog to build up and possible increases latency.

Rewiring these things in the transport agent doesn't seem too trivial, working on that :smile:

**Comment by sdroege** [comment] 2015-02-20 14:09
erdtlsenc also just drops data if the DTLS handshake is not finished yet.

**Comment by superdump** [comment] 2015-02-22 05:27
Right, it would be much nicer if no data was sent before the connection was established and then no RTP/RTCP before the DTLS handshake was complete. And no backlog of data was built up while waiting for those events to occur.

**Comment by sdroege** [comment] 2015-02-22 08:25
Yeah, working on that. If nothing else distracts me that should be done Monday or Tuesday :smile:

**Comment by ijsf** [comment] 2015-02-24 00:15
Can confirm this bug on iPad Mini 1, with current master. Additionally, I get occasional seconds of black video after a while. Performance is currently extremely slow and OpenWebRTC may be dropping frames of some kind.

**Comment by superdump** [comment] 2015-02-24 06:55
Does iPad Mini 1 support hardware H264? Are you using H264 or VP8? What is the other client? Currently if there is packet loss, a new key frame will be requested from the other side, packets will be thrown away until the full keyframe arrives and we can display completely good frames again. We need to test the error concealment capabilities of vtdec and openh264dec. I have a feeling that some of the codecs we use will do very good error concealment so that we don't have to be quite so aggressive.

We also implement real RTP retransmission now but I think other clients still do it using Google's non-standard method where RTX packets are sent with the same SSRC as the original stream.

Finally, what application are you using? The current bitmap rendering mechanism in Bowser is not at all optimal for mobile use, but it works well enough as a test bed and demonstrator. We're going to add an OpenGL overlay rendering method in Bowser soon which gives native performance. Other example apps already use this.

**Comment by stefanalund** [comment] 2015-02-24 08:22
Only devices with A7 chip (iPhone 5s and newer) can run H.264 in HW. The iPad Mini 1 is a quite slow device since it was using one year old CPU when released (same HW specs as iPad 2). If we can get OpenWebRTC running nicely on it we have well performing framework 😃

**Comment by superdump** [comment] 2015-02-24 08:34
I believe we can, it's just a matter of time. :smile:

**Comment by sdroege** [comment] 2015-02-24 08:42
RTX only helps when losing any packet after the first received one, so doesn't really help here :smile: 

Can we keep this ticket clean from other issues than the one mentioned at the very beginning? If we start to track random related or not related issues in the same ticket, things become confusing and problems can get lost.

**Comment by sdroege** [comment] 2015-02-25 12:13
I basically have it working btw, but for some reason the nice agent does not always tell me that it's ready

**Comment by sdroege** [comment] 2015-02-25 13:43
↑ there is an implementation for all this now. But I think libnice is currently too broken to implement this as it doesn't always tell us when the agent's component is set up and a pair was selected.

**Comment by stefanalund** [comment] 2015-03-03 12:10
Wasn't this issue fixed?

**Comment by sdroege** [comment] 2015-03-03 12:57
No, my commits above fix it but uncover a bug in libnice or our integration with libnice that I'm still looking into.

**Comment by ijsf** [comment] 2015-03-10 17:25
Just confirmed that I still do not have useful video on iPad Mini Gen 1. Video is either garbled, green or black, and only very rarely I have video for a few seconds. Not sure if that's all caused by this issue though.

**Comment by ijsf** [comment] 2015-03-28 02:27
The video issues mentioned in my last comment belong in this issue: https://github.com/EricssonResearch/openwebrtc/issues/260

**Comment by ijsf** [comment] 2015-04-09 23:41
@sdroege I can confirm this issue is likely causing my extreme latency issues on iOS.

@ikonst has helped me to debug this issue, the best test case appeared to be iOS NativeDemo <-> OS X test_client, in which we can see that a lot of buffers are discarded before the audio/video streams are even added (e.g. "pad-added" on transport_bin is called) and the decoding pipeline is set up:

**OS X test_client output with GST_DEBUG=*:2** https://gist.github.com/ijsf/1e1e9e3d102d8597b50c
**iOS NativeDemo output with GST_DEBUG=*:2** https://gist.github.com/ijsf/1e1e9e3d102d8597b50c

The few seconds that are wasted in invalid buffers appear to be the same amount of seconds of latency I'm getting.. and is fairly random each time a call is made.

**Comment by ikonst** [comment] 2015-04-10 17:08
> No, my commits above fix it but uncover a bug in libnice or our integration with libnice that I'm still looking into.

@sdroege - can you link to the libnice bug? Is it this -- https://bugs.freedesktop.org/show_bug.cgi?id=89673 ?

**Comment by sdroege** [comment] 2015-04-13 09:56
@ikonst no bug report yet, I don't know yet if it's a libnice bug or owr doing things wrong. Needs further debugging first

**Comment by alessandrod** [comment] 2015-10-13 02:19
So with https://github.com/alessandrod/openwebrtc/tree/delay-media-sending and https://github.com/EricssonResearch/cerbero/pull/32 this and other issues are gone. In particular this work makes latency between NativeDemo (ios) <=> firefox unnoticeable (when using h264) on a local network.

The delay-media-sending branch needs a little polish which i'm going to do now. In the meantime it would be great if someone could test h264 between ios and firefox and confirm that the latency issue is fixed.

**Comment by superdump** [comment] 2015-10-13 04:30
Excellent! I'll get on that (testing) today.

**Comment by stefanalund** [comment] 2015-10-13 06:56
Excited to try it out. @superdump let me know when you have a build ready.

**Comment by sdroege** [comment] 2015-10-13 07:43
@alessandrod you might want to squash together my commits before submitting a pull request too :) Thanks for working on this!

**Comment by superdump** [comment] 2015-10-14 07:13
@alessandrod - it works pretty well with VGA 768kbps between an iPhone 6 Plus and Firefox, and also between an iPhone 6 Plus and iPhone 6S. Latency is down to something sensible! :smile:

I had to add back a couple of variables in test_send_receive.c that had been removed in the 'foo' commit from @sdroege 's branch to get it building properly.

```diff
commit d9f28a5ff538e22a24965c4203ead1c8bdfaedaf
Author: Robert Swain <robert.swain@ericsson.com>
Date:   Tue Oct 13 11:36:41 2015 +0200

    test_send_receive: Add back missing declarations

diff --git a/tests/test_send_receive.c b/tests/test_send_receive.c
index 163b292..90c5146 100644
--- a/tests/test_send_receive.c
+++ b/tests/test_send_receive.c
@@ -45,8 +45,10 @@
 #include <string.h>

 static OwrTransportAgent *recv_transport_agent = NULL;
+static OwrMediaSession *recv_session_audio = NULL;
 static OwrMediaSession *recv_session_video = NULL;
 static OwrTransportAgent *send_transport_agent = NULL;
+static OwrMediaSession *send_session_audio = NULL;
 static OwrMediaSession *send_session_video = NULL;
 static OwrMediaRenderer *video_renderer = NULL;
 static OwrMediaRenderer *remote_video_renderer = NULL;
```

Other than that it seems to work. Thanks! And yes, squash those commits before making a PR please. :smile:

**Comment by alessandrod** [comment] 2015-10-20 04:33
Alright thanks for the feedback! I removed that debug commit in test-send-receive altogether, removed another and squashed the rest.

Owr PR: https://github.com/EricssonResearch/openwebrtc/pull/488
Cerbero PR: https://github.com/EricssonResearch/cerbero/pull/32

**Comment by alessandrod** [comment] 2015-11-24 01:41
We landed this a month ago and it hasn't introduced any major regressions. Can we close?

**Comment by superdump** [comment] 2015-11-24 05:42
Smells good to me. :)

**Closed by superdump** 2015-11-24 05:42 UTC
Labels: All Platforms, bug, enhancement, Non-Build Issue
