### ISSUE TITLE
How to trigger the got_remote_source openwebrtc method on another IOS device

### ISSUE THREAD

**Issue by WangHeng861021** [EricssonResearch/openwebrtc#460] opened 2015-08-19 13:31 UTC
Hi,in a LAN，we use two iPad to build connection in openwebrtc,but don't find a method to trigger the got_remote_source method,which is to bind owr_media_render with the remote owr_media_source,please give some advise about it,that's the last step to build a connection successfully.

**Comment by superdump** [comment] 2015-08-31 06:37
Closing as a duplicate of #459

**Closed by superdump** 2015-08-31 06:37 UTC
