### ISSUE TITLE
Error(s) while building webRTC on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by dranz3r** [EricssonResearch/openwebrtc#371] opened 2015-05-12 12:47 UTC
Hi all,

I've been up for the last 2 nights just trying to figure out why these scripts won't compile. I've scrapped my entire Ubuntu OS to get a fresh copy and started compiling these scripts even before I got my nVidia drivers on. Still (fucking hell) I'm having a few issues still while compiling the linux and android versions. Here's a thread for the linux version. The below is the first of a few issues I'm having. Can some one explain how to get around this one? If I do a skip recipe here, would it negatively impact my openWebRTC build? All I need are the .jar files so I can work on the actual code. And some good night's sleep after I have a bit of the code working. *smh*

Help!!!

Issue 1:
[(21/35) gst-plugins-bad-1.0-static -> fetch ]
-----> Step done
[(21/35) gst-plugins-bad-1.0-static -> extract ]
-----> Step done
[(21/35) gst-plugins-bad-1.0-static -> configure ]
-----> Step done
[(21/35) gst-plugins-bad-1.0-static -> compile ]
-----> Step done
[(21/35) gst-plugins-bad-1.0-static -> install ]
-----> Step done
[(21/35) gst-plugins-bad-1.0-static -> post_install ]
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/_username/cerbero/sources/linux_x86_64/gst-plugins-bad-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopenh264.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/_username/cerbero/sources/linux_x86_64/gst-plugins-bad-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopus.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/_username/cerbero/sources/linux_x86_64/gst-plugins-bad-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoparsersbad.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/_username/cerbero/sources/linux_x86_64/gst-plugins-bad-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstinter.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/_username/cerbero/sources/linux_x86_64/gst-plugins-bad-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstsrtp.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/_username/cerbero/sources/linux_x86_64/gst-plugins-bad-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstdtls.la'

Recipe 'gst-plugins-bad-1.0-static' failed at the build step 'post_install'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "/home/_username/cerbero/recipes/custom.py", line 93, in post_install
    shutil.copyfile(src, dest)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/_username/cerbero/sources/linux_x86_64/gst-plugins-bad-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopengl.a'

Issue 2:
[(28/35) libusrsctp -> fetch ]
/bin/sh: 1: svn: not found
Running command 'rm -rf /home/_username/cerbero/sources/local/libusrsctp-master'
Running command 'svn co http://sctp-refimpl.googlecode.com/svn/trunk/KERN/usrsctp /home/_username/cerbero/sources/local/libusrsctp-master'

Recipe 'libusrsctp' failed at the build step 'fetch'

Comment for Issue 2: The internet is all setup and working so not sure why the fetch command won't work. I'm assuming the code was moved?

Issue 3: 
[(28/35) openwebrtc-gst-plugins -> fetch ]
-----> Step done
[(28/35) openwebrtc-gst-plugins -> extract ]
-----> Step done
[(28/35) openwebrtc-gst-plugins -> configure ]
-----> copying /home/_username/cerbero/data/autotools/config.guess to /home/_username/cerbero/sources/linux_x86_64/openwebrtc-gst-plugins-0.3.0/config.guess
-----> copying /home/_username/cerbero/data/autotools/config.sub to /home/_username/cerbero/sources/linux_x86_64/openwebrtc-gst-plugins-0.3.0/config.sub
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /home/_username/cerbero/build-tools/bin/autoconf --force
autoreconf: running: /home/_username/cerbero/build-tools/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:21: installing './compile'
configure.ac:15: installing './missing'
ext/sctp/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
configure: WARNING: unrecognized options: --disable-erdtls, --enable-introspection
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU Objective C compiler... no
checking whether gcc accepts -g... no
checking dependency style of gcc... gcc3
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... ld
checking if the linker (ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... nm
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse nm output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... cpp
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... ld -m elf_x86_64
checking if the linker (ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking pkg-config is at least version 0.9.0... yes
checking for GST... yes
checking to see if compiler understands -Wall... yes
checking usrsctp.h usability... no
checking usrsctp.h presence... no
checking for usrsctp.h... no
configure: error: You need libusrsctp for the build
Running command 'mkdir -p m4 && autoreconf -fiv'
Running command './configure --prefix /opt/openwebrtc-0.3 --libdir /opt/openwebrtc-0.3/lib              --enable-shared             --enable-static             --disable-erdtls             --disable-debug             --disable-static-plugins             --disable-android-plugins             --disable-osx-plugins             --disable-linux-plugins --disable-colorspace-converter --enable-linux-plugins --disable-maintainer-mode  --disable-silent-rules  --enable-introspection '

Recipe 'openwebrtc-gst-plugins' failed at the build step 'configure'

Comments on Issue 3: This relates to Issue 2. "configure: error: You need libusrsctp for the build"

**Comment by dranz3r** [comment] 2015-05-12 12:52
Issue 4: 
[(31/35) openwebrtc -> fetch ]
-----> Step done
[(31/35) openwebrtc -> extract ]
-----> Step done
[(31/35) openwebrtc -> configure ]
-----> copying /home/_username/cerbero/data/autotools/config.guess to /home/_username/cerbero/sources/linux_x86_64/openwebrtc-0.3.0/config.guess
-----> copying /home/_username/cerbero/data/autotools/config.sub to /home/_username/cerbero/sources/linux_x86_64/openwebrtc-0.3.0/config.sub
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:21: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:21: the top level
configure.ac:21: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:21: the top level
autoreconf: configure.ac: tracing
configure.ac:21: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:21: the top level
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:21: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:21: the top level
configure.ac:21: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:21: the top level
autoreconf: running: /home/_username/cerbero/build-tools/bin/autoconf --force
configure.ac:21: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:21: the top level
autoreconf: running: /home/_username/cerbero/build-tools/bin/autoheader --force
configure.ac:21: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:21: the top level
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:21: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:21: the top level
configure.ac:18: installing './compile'
configure.ac:14: installing './missing'
bindings/java/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
configure: WARNING: unrecognized options: --disable-maintainer-mode
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking for gcc... gcc
checking whether we are using the GNU Objective C compiler... no
checking whether gcc accepts -g... no
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc -std=gnu99... ld
checking if the linker (ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... nm
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse nm output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... cpp
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... yes
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking for GSTREAMER... yes
checking for NICE... yes
checking for GSTREAMER_SCTP... no
configure: error: Package requirements (gstreamer-sctp-1.0) were not met:

No package 'gstreamer-sctp-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GSTREAMER_SCTP_CFLAGS
and GSTREAMER_SCTP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Running command 'mkdir -p m4 && gtkdocize && autoreconf -fiv'
Running command './configure --prefix /opt/openwebrtc-0.3 --libdir /opt/openwebrtc-0.3/lib  --enable-gtk-doc --disable-static                 --disable-owr-static --enable-shared --enable-tests --enable-gtk-doc --disable-maintainer-mode  --disable-silent-rules  --enable-introspection '

Recipe 'openwebrtc' failed at the build step 'configure'

**Comment by dranz3r** [comment] 2015-05-12 12:54
Issue 5: 
[(31/35) openwebrtc-gst-plugins-static -> fetch ]
-----> Step done
[(31/35) openwebrtc-gst-plugins-static -> extract ]
-----> Step done
[(31/35) openwebrtc-gst-plugins-static -> configure ]
-----> copying /home/_username/cerbero/data/autotools/config.guess to /home/_username/cerbero/sources/linux_x86_64/openwebrtc-gst-plugins-static-0.3.0/config.guess
-----> copying /home/_username/cerbero/data/autotools/config.sub to /home/_username/cerbero/sources/linux_x86_64/openwebrtc-gst-plugins-static-0.3.0/config.sub
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /home/_username/cerbero/build-tools/bin/autoconf --force
autoreconf: running: /home/_username/cerbero/build-tools/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:21: installing './compile'
configure.ac:15: installing './missing'
ext/sctp/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /home/_username/cerbero/build-tools/bin/autoconf --force
autoreconf: running: /home/_username/cerbero/build-tools/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:21: installing './compile'
configure.ac:15: installing './missing'
ext/sctp/Makefile.am: installing './depcomp'
autoreconf: no config.status: cannot re-make
autoreconf: Leaving directory `.'
configure: WARNING: unrecognized options: --enable-introspection, --disable-examples, --disable-erdtls, --enable-introspection
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU Objective C compiler... no
checking whether gcc accepts -g... no
checking dependency style of gcc... gcc3
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... ld
checking if the linker (ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... nm
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse nm output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... cpp
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... ld -m elf_x86_64
checking if the linker (ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking pkg-config is at least version 0.9.0... yes
checking for GST... yes
checking to see if compiler understands -Wall... yes
checking usrsctp.h usability... no
checking usrsctp.h presence... no
checking for usrsctp.h... no
configure: error: You need libusrsctp for the build
Running command 'mkdir -p m4 && autoreconf -fiv'
Running command 'sh ./autogen.sh --noconfigure && ./configure --prefix /opt/openwebrtc-0.3 --libdir /opt/openwebrtc-0.3/lib --enable-introspection=no --disable-examples --enable-static-plugins --disable-shared --enable-static              --disable-erdtls             --disable-debug             --disable-android-plugins             --disable-osx-plugins             --disable-linux-plugins --disable-colorspace-converter --enable-linux-plugins  --disable-maintainer-mode  --disable-silent-rules  --enable-introspection '

Recipe 'openwebrtc-gst-plugins-static' failed at the build step 'configure'

**Comment by PerBoussard** [comment] 2015-05-12 14:00
I may be wrong, but it looks like you're missing an svn client?
Den 12 maj 2015 15:54 skrev "dranz3r" <notifications@github.com>:

**Comment by dranz3r** [comment] 2015-05-12 14:01
Oh...I'll take a look. I'm assuming you're talking about Issue 1?

**Comment by PerBoussard** [comment] 2015-05-12 14:11
Yes. All that follows may be caused by a missing svn client from the looks
of it.
Den 12 maj 2015 17:01 skrev "dranz3r" <notifications@github.com>:

**Comment by superdump** [comment] 2015-05-12 14:15
Yup. ´sudo apt-get install subversion´

**Comment by dranz3r** [comment] 2015-05-12 14:16
@PerBoussard  Thanks for that. This solved Issues No. 2 and 3 from the first comment. Waiting for the gst-plugins-bad-1.0-static to do its post install steps before I can verify. And yes, I found the line that says "Missing svn". I should have slept. :-|

@superdump  Thanks!

**Comment by superdump** [comment] 2015-05-12 14:17
Note that if you just want the jar files for Android, we made a release not long ago: https://github.com/EricssonResearch/openwebrtc/releases

**Comment by dranz3r** [comment] 2015-05-12 14:25
@superdump So you're saying I did not have to do all this? Could you please add this comment about releases that are already there on the thread where people get the info about building this so they don't have to assume thats the only way to get started? Or was it there and I completely missed it? I finally found the releases from the main GitHub page. I guess I'm a noob at github. 




FUUUUUUUUUUUUUUUUUUUUCCCCCCCCCCCCCCCCCCCCCCCCCKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

I apologize but I'm not sure about the cursing policies on github. If this offends anyone, I'll remove it.

**Comment by dranz3r** [comment] 2015-05-12 14:27
I would like to say that the comments helped. Out of the 5 issues I was having, it has narrowed down to just the one issue that I still have. I'll go this route considering I'm so close to building it on my machine.  Any ideas on this one?

Recipe 'gst-plugins-bad-1.0-static' failed at the build step 'post_install'

This is the same issue as highlighted in first comment under Issue 1.

**Comment by superdump** [comment] 2015-05-12 14:30
I'll have to investigate that one. I've seen it too. It's probably some missing GL packages from the bootstrap like subversion is also missing.

I added a note at the beginning of the Building OpenWebRTC wiki page with a link to the releases. I'll add it to the README.md too. Apologies for the inconvenience.

**Comment by dranz3r** [comment] 2015-05-12 14:33
@superdump  No worries. Thanks much! So should I leave this issue open for now while you investigate or do you want me to close it? Also, I was unable to put labels on this issue but I'm assuming "Build" and "Linux" and "Idiot" would work. :)

**Comment by superdump** [comment] 2015-05-12 14:42
Haha. I think we can close this one and I'll create a new issue about the missing dependencies on Linux. Thanks for the report. :smile:

**Closed by superdump** 2015-05-12 14:42 UTC

**Comment by dranz3r** [comment] 2015-05-12 14:43
@superdump @PerBoussard Thanks for the quick responses.
